FROM quay.io/erasche/chado-schema-builder-base:latest

RUN mkdir -p $GMOD_ROOT /build && \
    chown postgres:postgres /build

ADD load.conf.tt2 /opt/load.conf.tt2
ADD cvtermpath_fix.sql /opt/cvtermpath_fix.sql
ADD update_urls.sql /opt/update_urls.sql
ADD fix_relationshiptype_lc.diff /opt/fix_relationshiptype_lc.diff
ADD obo_extract_typedefs.py /opt/obo_extract_typedefs.py
RUN chown postgres: -R /opt/ /usr/local/bin/ /usr/local/man/ && \
    chmod ug+rwx /usr/local/man

ADD build.sh /docker-entrypoint-initdb.d/build.sh
